# Generated by Django 3.2 on 2021-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=30)),
                ('min_age', models.IntegerField()),
                ('postal_codes', models.TextField(default='[]')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('phone', models.CharField(blank=True, default='', max_length=12)),
                ('hours', models.TextField(blank=True, default='')),
                ('submitted_from', models.CharField(choices=[('USER', 'User'), ('TWITTER', 'Twitter'), ('CC', 'Community Centre')], max_length=30)),
                ('url', models.CharField(blank=True, default='', max_length=2000)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending')], default='Pending', max_length=8)),
            ],
        ),
    ]
