# Generated by Django 3.2 on 2021-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='postal_codes',
            field=models.TextField(default=''),
        ),
    ]
